encoding: UTF-8
# theme: jekyll-theme-leap-day - now replaced by JTD
remote_theme: just-the-docs/just-the-docs
title: Ozaru.Net
description: Ōzaru test site
logo: "/assets/images/Ozaru-logo-nobooks.png" #takes precedence over 'Title', in side-bar navigation
# Aux links for the upper right navigation
aux_links:
  "Home":
    - "/index"
github:
  is_project_page: false
